import { useState, useEffect } from 'react';
import { Play, Pause, SkipForward, SkipBack, Volume2, Sliders, Disc, Radio } from 'lucide-react';
import { Track } from '../types';
import { audioEngine } from '../utils/audioEngine';
import AudioVisualizer from './AudioVisualizer';

// Import our custom images generated by AI
import cyberHorizonCover from '../assets/images/cyber_horizon_cover_1779599402459.png';
import neonGlitchCover from '../assets/images/neon_glitch_cover_1779599422861.png';
import vaporChillCover from '../assets/images/vapor_chill_cover_1779599440045.png';

interface MusicPlayerProps {
  onTrackChange: (track: Track) => void;
  onAudioInit: () => void;
  isPlayingGlobal: boolean;
  setIsPlayingGlobal: (playing: boolean) => void;
}

export const TRACKS: Track[] = [
  {
    id: 'cyber-horizon',
    title: 'Cyber Horizon',
    genre: 'Synthwave / Outrun',
    bpm: 120,
    description: 'Energetic driving retrowave beat. Perfect rhythm for steady runs.',
    duration: '01:54',
    color: 'emerald',
    glowColor: '16, 185, 129',
  },
  {
    id: 'neon-glitch',
    title: 'Neon Glitch',
    genre: 'Chiptune / Bitpop',
    bpm: 142,
    description: 'Hyper-paced chip tunes. Amplifies speed and reaction times.',
    duration: '01:21',
    color: 'fuchsia',
    glowColor: '217, 70, 239',
  },
  {
    id: 'vapor-chill',
    title: 'Vapor Chill',
    genre: 'Vaporwave / Chill',
    bpm: 92,
    description: 'Dreamy, slow-wave resonant ambient. Ideal for high score practice.',
    duration: '02:30',
    color: 'cyan',
    glowColor: '6, 182, 212',
  },
];

const COVERS: Record<string, string> = {
  'cyber-horizon': cyberHorizonCover,
  'neon-glitch': neonGlitchCover,
  'vapor-chill': vaporChillCover,
};

const SHADOW_COLOR: Record<string, string> = {
  emerald: 'shadow-emerald-500/20 border-emerald-500/40 text-emerald-400',
  fuchsia: 'shadow-fuchsia-500/20 border-fuchsia-500/40 text-fuchsia-400',
  cyan: 'shadow-cyan-500/20 border-cyan-500/40 text-cyan-400',
};

const GLOW_HEX: Record<string, string> = {
  emerald: '#10b981',
  fuchsia: '#d946ef',
  cyan: '#06b6d4',
};

export default function MusicPlayer({ 
  onTrackChange, 
  onAudioInit, 
  isPlayingGlobal, 
  setIsPlayingGlobal 
}: MusicPlayerProps) {
  const [currentIdx, setCurrentIdx] = useState(0);
  const [volume, setVolume] = useState(0.4);
  const [filterCutoff, setFilterCutoff] = useState(0.8);
  const [analyser, setAnalyser] = useState<AnalyserNode | null>(null);

  const activeTrack = TRACKS[currentIdx];

  const handleInitAudio = () => {
    onAudioInit();
    const node = audioEngine.getAnalyser();
    if (node) setAnalyser(node);
  };

  // Sync volume change
  useEffect(() => {
    audioEngine.setVolume(volume);
  }, [volume]);

  // Sync EQ Filter
  useEffect(() => {
    audioEngine.setFilterCutoff(filterCutoff);
  }, [filterCutoff]);

  // Handle Play/Pause
  const togglePlay = () => {
    handleInitAudio();
    if (isPlayingGlobal) {
      audioEngine.pause();
      setIsPlayingGlobal(false);
    } else {
      audioEngine.play(activeTrack.id, activeTrack.bpm);
      setIsPlayingGlobal(true);
    }
  };

  const nextTrack = () => {
    handleInitAudio();
    const nextIdx = (currentIdx + 1) % TRACKS.length;
    setCurrentIdx(nextIdx);
    onTrackChange(TRACKS[nextIdx]);
    
    if (isPlayingGlobal) {
      audioEngine.play(TRACKS[nextIdx].id, TRACKS[nextIdx].bpm);
    }
  };

  const prevTrack = () => {
    handleInitAudio();
    const prevIdx = (currentIdx - 1 + TRACKS.length) % TRACKS.length;
    setCurrentIdx(prevIdx);
    onTrackChange(TRACKS[prevIdx]);

    if (isPlayingGlobal) {
      audioEngine.play(TRACKS[prevIdx].id, TRACKS[prevIdx].bpm);
    }
  };

  const selectTrack = (idx: number) => {
    handleInitAudio();
    setCurrentIdx(idx);
    onTrackChange(TRACKS[idx]);
    if (isPlayingGlobal) {
      audioEngine.play(TRACKS[idx].id, TRACKS[idx].bpm);
    } else {
      audioEngine.play(TRACKS[idx].id, TRACKS[idx].bpm);
      setIsPlayingGlobal(true);
    }
    audioEngine.triggerSfx('keypress');
  };

  // Trigger setup on mounting and initial track info push
  useEffect(() => {
    onTrackChange(activeTrack);
  }, []);

  return (
    <div 
      id="music-console"
      className="p-5 bg-[#080808] border border-zinc-800 rounded-2xl shadow-[0_0_50px_rgba(0,0,0,0.8)] backdrop-blur-md flex flex-col gap-5 h-full relative overflow-hidden"
    >
      {/* Visual background wireframe grid decoration */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,rgba(255,255,255,0.01)_1px,transparent_1px)] bg-[size:16px_16px] pointer-events-none" />

      {/* Header Info */}
      <div className="flex justify-between items-center border-b border-zinc-800 pb-3 relative z-10">
        <div className="flex items-center gap-2">
          <div className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse shadow-[0_0_10px_#22d3ee]" />
          <h2 className="text-sm font-orbitron font-bold text-zinc-200 tracking-wider">NEON SYNTH AUDIO</h2>
        </div>
        <div className="flex gap-1.5 text-[10px] font-mono text-cyan-400 bg-cyan-950/20 px-2 py-0.5 rounded border border-cyan-500/20">
          <Radio className="w-3 h-3 animate-pulse" />
          <span>LIVE SYNTH</span>
        </div>
      </div>

      {/* Active Track Artwork & Spindle */}
      <div className="flex flex-col sm:flex-row gap-4 items-center relative z-10">
        <div className="relative group w-28 h-28 sm:w-32 sm:h-32 flex-shrink-0 bg-[#050505] rounded-xl overflow-hidden border border-zinc-800 shadow-[0_0_15px_rgba(0,0,0,0.5)]">
          <img 
            src={COVERS[activeTrack.id]} 
            alt={activeTrack.title}
            className={`w-full h-full object-cover select-none transition-transform duration-700 ${isPlayingGlobal ? 'scale-105' : 'scale-100'}`}
            referrerPolicy="no-referrer"
          />
          {/* Virtual Vinyl Center Spindle */}
          <div className="absolute inset-0 flex items-center justify-center bg-black/30">
            <div className={`w-10 h-10 rounded-full bg-black/90 flex items-center justify-center border-2 border-dashed ${isPlayingGlobal ? 'animate-spin border-fuchsia-500' : 'border-zinc-800'}`}>
              <Disc className={`w-5 h-5 ${isPlayingGlobal ? 'text-fuchsia-400' : 'text-zinc-600'}`} />
            </div>
          </div>
        </div>

        {/* Text details */}
        <div className="flex-1 min-w-0 text-center sm:text-left">
          <span className="text-[10px] font-mono text-fuchsia-400 uppercase tracking-widest">{activeTrack.genre}</span>
          <h3 className="text-xl font-orbitron font-extrabold text-zinc-100 mt-0.5 tracking-tight truncate">
            {activeTrack.title}
          </h3>
          <p className="text-xs text-zinc-400 mt-1.5 leading-relaxed font-sans line-clamp-2">
            {activeTrack.description}
          </p>
          <div className="mt-2.5 flex flex-wrap justify-center sm:justify-start items-center gap-2 text-[10px] font-mono text-zinc-500">
            <span className="bg-black/40 border border-zinc-800 px-2 py-0.5 rounded text-cyan-400">
              {activeTrack.bpm} BPM
            </span>
            <span className="bg-black/40 border border-zinc-800 px-2 py-0.5 rounded">
              LEN: {activeTrack.duration}
            </span>
          </div>
        </div>
      </div>

      {/* Real-time Spectrum Visualizer */}
      <div className="h-20 sm:h-24 w-full relative z-10">
        <AudioVisualizer 
          analyser={analyser} 
          isPlaying={isPlayingGlobal} 
          color={GLOW_HEX[activeTrack.color]} 
          glowColor={activeTrack.glowColor} 
        />
      </div>

      {/* Cassette Mechanical Wheels Visualization */}
      <div className="p-3 bg-black/40 rounded-xl border border-zinc-800 flex items-center justify-between gap-5 text-zinc-500 relative overflow-hidden">
        <div className="absolute top-1 left-2 text-[8px] font-mono text-zinc-600 tracking-wider">TAPE FEED A</div>
        <div className="w-12 h-12 rounded-full border border-zinc-800/80 bg-black/50 flex items-center justify-center transition-all duration-300">
          <div className={`w-8 h-8 rounded-full border-2 border-dashed border-zinc-700/30 flex items-center justify-center ${isPlayingGlobal ? 'animate-[spin_4s_linear_infinite]' : ''}`}>
            <span className="w-1.5 h-1.5 rounded-full bg-zinc-600" />
          </div>
        </div>
        <div className="flex-1 h-1.5 bg-black border border-zinc-900 rounded-full relative overflow-hidden">
          <div 
            className="h-full bg-gradient-to-r from-cyan-500 to-fuchsia-500 transition-all duration-300 shadow-[0_0_8px_rgba(6,182,212,0.8)]" 
            style={{ width: isPlayingGlobal ? '58%' : '40%' }} 
          />
        </div>
        <div className="w-12 h-12 rounded-full border border-zinc-800/80 bg-black/50 flex items-center justify-center transition-all duration-300">
          <div className={`w-8 h-8 rounded-full border-2 border-dashed border-zinc-700/30 flex items-center justify-center ${isPlayingGlobal ? 'animate-[spin_4s_linear_infinite]' : ''}`}>
            <span className="w-1.5 h-1.5 rounded-full bg-zinc-600" />
          </div>
        </div>
      </div>

      {/* Control buttons & Sliders */}
      <div className="flex flex-col gap-4 relative z-10 w-full">
        {/* Main Buttons */}
        <div className="flex items-center justify-between gap-2.5">
          <button 
            id="prev-track"
            onClick={prevTrack}
            className="p-2 sm:p-2.5 rounded-xl border border-zinc-800 hover:border-zinc-700 hover:bg-zinc-905 text-zinc-300 active:scale-95 transition-all cursor-pointer"
            title="Previous Track"
          >
            <SkipBack className="w-5 h-5" />
          </button>

          <button 
            id="toggle-playback"
            onClick={togglePlay}
            className={`flex-1 flex items-center justify-center gap-2 py-2.5 sm:py-3 px-5 rounded-xl text-xs font-orbitron font-bold tracking-widest uppercase transition-all duration-300 transform active:scale-98 shadow-md cursor-pointer ${
              isPlayingGlobal 
                ? 'bg-gradient-to-r from-red-600/10 to-orange-600/5 border border-red-500/40 text-red-200' 
                : 'bg-cyan-500 hover:bg-cyan-400 text-black shadow-[0_0_20px_rgba(6,182,212,0.4)]'
            }`}
          >
            {isPlayingGlobal ? (
              <>
                <Pause className="w-4 h-4 fill-red-200" />
                <span>PAUSE STREAM</span>
              </>
            ) : (
              <>
                <Play className="w-4 h-4 fill-black animate-pulse" />
                <span>PLAY SOUND</span>
              </>
            )}
          </button>

          <button 
            id="next-track"
            onClick={nextTrack}
            className="p-2 sm:p-2.5 rounded-xl border border-zinc-800 hover:border-zinc-700 hover:bg-zinc-905 text-zinc-300 active:scale-95 transition-all cursor-pointer"
            title="Next Track"
          >
            <SkipForward className="w-5 h-5" />
          </button>
        </div>

        {/* Audio parameter adjustments (Volume & Cutoff) */}
        <div className="grid grid-cols-2 gap-3 p-3 bg-black/40 rounded-xl border border-zinc-805">
          {/* Volume Control */}
          <div className="flex flex-col gap-1.5">
            <div className="flex justify-between items-center text-[10px] font-mono text-zinc-400">
              <span className="flex items-center gap-1">
                <Volume2 className="w-3 h-3 text-cyan-400" /> VOLUME
              </span>
              <span>{Math.round(volume * 100)}%</span>
            </div>
            <input 
              type="range"
              min="0"
              max="1"
              step="0.01"
              value={volume}
              onChange={(e) => setVolume(parseFloat(e.target.value))}
              className="w-full accent-cyan-400 h-1 bg-zinc-800 rounded-lg appearance-none cursor-pointer"
            />
          </div>

          {/* Low Pass Cutoff */}
          <div className="flex flex-col gap-1.5">
            <div className="flex justify-between items-center text-[10px] font-mono text-zinc-400">
              <span className="flex items-center gap-1">
                <Sliders className="w-3 h-3 text-fuchsia-400" /> EQ CO-RESONANCE
              </span>
              <span>{Math.round(filterCutoff * 100)}%</span>
            </div>
            <input 
              type="range"
              min="0.05"
              max="1"
              step="0.01"
              value={filterCutoff}
              onChange={(e) => setFilterCutoff(parseFloat(e.target.value))}
              className="w-full accent-fuchsia-400 h-1 bg-zinc-800 rounded-lg appearance-none cursor-pointer"
            />
          </div>
        </div>
      </div>

      {/* Playlist Selector Grid */}
      <div className="flex flex-col gap-2 relative z-10">
        <span className="text-[10px] font-mono font-bold tracking-wider text-zinc-500 uppercase">SYNTH BANK CHANNELS</span>
        <div className="flex flex-col gap-1.5 max-h-44 overflow-y-auto pr-1 scrollbar-thin scrollbar-thumb-zinc-800 scrollbar-track-transparent">
          {TRACKS.map((track, idx) => {
            const isSelected = idx === currentIdx;
            const style = SHADOW_COLOR[track.color];
            return (
              <button
                key={track.id}
                onClick={() => selectTrack(idx)}
                className={`w-full flex items-center justify-between p-2 rounded-xl text-left border relative transition-all duration-200 text-xs font-mono cursor-pointer ${
                  isSelected 
                    ? `bg-[#0c0c0c] border-zinc-700 shadow-sm ${style}` 
                    : 'bg-black/20 border-zinc-900/60 text-zinc-500 hover:text-zinc-300 hover:border-zinc-800 hover:bg-zinc-900/10'
                }`}
              >
                <div className="flex items-center gap-2.5 min-w-0">
                  <span className={`w-1.5 h-1.5 rounded-full ${isSelected ? 'bg-current animate-ping' : 'bg-zinc-800'}`} />
                  <img 
                    src={COVERS[track.id]} 
                    alt={track.title}
                    className="w-7 h-7 object-cover rounded border border-zinc-800 flex-shrink-0"
                    referrerPolicy="no-referrer"
                  />
                  <div className="min-w-0">
                    <div className="font-orbitron font-bold text-zinc-200 truncate">{track.title}</div>
                    <div className="text-[9px] text-zinc-500 uppercase tracking-widest truncate">{track.genre}</div>
                  </div>
                </div>
                <div className="text-right flex-shrink-0 flex items-center gap-2 text-[10px]">
                  <span className="opacity-70">{track.bpm} BPM</span>
                  <span className="text-[8px] opacity-40">|</span>
                  <span className="opacity-80 font-mono">{track.duration}</span>
                </div>
              </button>
            );
          })}
        </div>
      </div>
    </div>
  );
}
